### ISSUE TITLE
Avoid using caret in versioning of Go and Node in CI Job

### ISSUE THREAD

**Issue by duyndh** [gobench-io/gobench#172]
I think we should not use caret when setting up the environment in CI to avoid compatible issues between deps.

Currently: 

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Set up Nodejs 14
      uses: actions/setup-node@v2
      with:
        node-version: ^14.15
      id: node

CI will use Go 1.20.5 and Node 14.21.3

**Comment by nguyencatpham** [comment]
Go: should support the last 2 versions
@hieult1393 will choose 1 Node version supported

**Comment by hieult1393** [comment]
@duyndh @nguyencatpham I think we could use Node version **16.20.1**

**Comment by nguyencatpham** [comment]
already resolve by #174 and #168
